[frontends.tcp_80]
listen_addr = "192.168.1.148:80"
backend = "tcp80_out"
  [frontends.tcp_80.xdp]
  bpf_program_path = "./af_xdp_kern.o"
  progsec_name = "xdp_filter_80"
  xsks_map_name = "xsks_map"

[backends.tcp80_out]
  health_check_interval = 3
  [backends.tcp80_out.servers]
    [backends.tcp80_out.servers.server1]
    addr = "hostname"
    port = 7001

[stats]
port = "7000"

[passthrough]
connection_tracker_capacity = 20000
workers = 2
stats_update_frequency = 5
